name: MLflow CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev \
                                libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
                                libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
                                liblzma-dev git
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow

    - name: Run MLflow Project
      run: python scripts/train_model.py

    - name: Evaluate model
      run: python scripts/evaluate_model.py --model_name SimpleNN --model_version 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlflow_cicd:latest .  # 빌드 컨텍스트를 현재 디렉토리로 설정
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow_cicd:latest

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name mlflow_cicd_container ${{ secrets.DOCKER_USERNAME }}/mlflow_cicd:latest
        sleep 10

    - name: Test Docker container
      run: |
        docker exec mlflow_cicd_container python /scripts/train_model.py
        docker exec mlflow_cicd_container python /scripts/evaluate_model.py --model_name SimpleNN --model_version 1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mlruns
        path: mlruns/
