name: MLflow CI/CD

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때마다 해당 워크플로우 실행

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions가 제공하는 최신 Ubuntu 환경에서 실행

    steps:
    - uses: actions/checkout@v2  # 리포지토리의 코드를 체크아웃하는 액션

    - name: Set up Python
      uses: actions/setup-python@v2  # Python 환경을 설정하는 액션
      with:
        python-version: '3.8'  # Python 3.8 버전을 사용

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
          libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
          liblzma-dev git
        python -m pip install --upgrade pip  # pip을 최신 버전으로 업그레이드
        pip install -r requirements.txt  # requirements.txt 파일에 명시된 의존성 패키지 설치
        pip install mlflow  # MLflow 설치

    - name: Run MLflow Project
      run: python ../scripts/train_model.py  # MLflow 프로젝트 실행

    - name: Evaluate model
      run: python ../scripts/evaluate_model.py --model_name SimpleNN --model_version 1  # MLflow 프로젝트 평가 실행

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Docker Buildx를 설정하여 멀티 플랫폼 빌드 가능

    - name: Log in to Docker Hub
      uses: docker/login-action@v1  # Docker Hub에 로그인하는 액션
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에 저장된 Docker Hub 사용자명
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에 저장된 Docker Hub 비밀번호

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mnist_cicd:latest .  # 현재 디렉토리에서 Docker 이미지를 빌드하고 'latest' 태그를 붙임
        docker push ${{ secrets.DOCKER_USERNAME }}/mnist_cicd:latest  # 빌드된 이미지를 Docker Hub에 푸시
