name: MLOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv mlflow-env
        source mlflow-env/bin/activate
        pip install -r requirements.txt
        pip install torch torchvision torchaudio

    - name: Build Docker image
      run: |
        docker build -t your_dockerhub_username/mlflow_cicd:latest .

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        docker push your_dockerhub_username/mlflow_cicd:latest
